# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Audio-Scrobbler
version:      0.01
version_from: lib/Audio/Scrobbler.pm
installdirs:  site
requires:
    Config::IniFiles:              2
    Digest::MD5:                   2
    LWP:                           5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
